### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Christofon** [Christofon/deploy-sol-plasm#1]
- [x] Make a simple Solidity contract. You can see flipper.sol here

- [ ] Compile the contract by using Solang.

- [ ] Join Discord and request PLD token (Dusty Network Token)

- [ ] Deploy that contract on Dusty Network from here (Click the logo→Testnet→Dusty)

- [ ] Upload the contract address on the GitHub thread below.
